### ISSUE TITLE
Can't get syslog relay to work

### ISSUE THREAD

**Issue by asapkota** [zuckschwerdt/rtl_433_relay#1]
I cannot get syslog relay to work. I have mqtt server that requires auth. I adjusted the script to pass the auth and it connects. But when rtl_433 detects device, I never get a message on MQTT server. I can see devices triggering rtl_433 when I run it with -F json. Any help is appreciated. Thanks

**Comment by zuckschwerdt** [comment]
Check port numbers and host/listen (`UDP_PORT`, `UDP_IP` vs -F syslog:127.0.0.1:1433)
Add logging (`print`) inside the while loop and see if data gets in, is processed and gets out.

**Comment by asapkota** [comment]
Checked the syslog info and added print. Here is the response. Should be messages be repeating 7 times like below? Also what is the 'u' in front of each field? Thanks

Tuned to 433920000 Hz.
MQTT connected: Connection Accepted.
{u'model': u'Akhan 100F14 remote keyless entry', u'data': u'0x8 (Alarm)', u'id': 503470, u'time': u'2018-05-08 08:00:21'}
{u'model': u'Akhan 100F14 remote keyless entry', u'data': u'0x8 (Alarm)', u'id': 503470, u'time': u'2018-05-08 08:00:21'}
{u'model': u'Akhan 100F14 remote keyless entry', u'data': u'0x8 (Alarm)', u'id': 503470, u'time': u'2018-05-08 08:00:21'}
{u'model': u'Akhan 100F14 remote keyless entry', u'data': u'0x8 (Alarm)', u'id': 503470, u'time': u'2018-05-08 08:00:21'}
{u'model': u'Akhan 100F14 remote keyless entry', u'data': u'0x8 (Alarm)', u'id': 503470, u'time': u'2018-05-08 08:00:21'}
{u'model': u'Akhan 100F14 remote keyless entry', u'data': u'0x8 (Alarm)', u'id': 503470, u'time': u'2018-05-08 08:00:21'}
{u'model': u'Akhan 100F14 remote keyless entry', u'data': u'0x8 (Alarm)', u'id': 503470, u'time': u'2018-05-08 08:00:21'}
{u'model': u'Generic Remote', u'cmd': 3, u'id': 55263, u'tristate': u'1FF11F110001', u'time': u'2018-05-08 08:00:26'}
{u'model': u'Generic Remote', u'cmd': 3, u'id': 55263, u'tristate': u'1FF11F110001', u'time': u'2018-05-08 08:00:26'}
{u'model': u'Generic Remote', u'cmd': 3, u'id': 55263, u'tristate': u'1FF11F110001', u'time': u'2018-05-08 08:00:26'}
{u'model': u'Generic Remote', u'cmd': 3, u'id': 55263, u'tristate': u'1FF11F110001', u'time': u'2018-05-08 08:00:26'}
{u'model': u'Generic Remote', u'cmd': 3, u'id': 55263, u'tristate': u'1FF11F110001', u'time': u'2018-05-08 08:00:26'}
{u'model': u'Generic Remote', u'cmd': 3, u'id': 55263, u'tristate': u'1FF11F110001', u'time': u'2018-05-08 08:00:26'}
{u'model': u'Generic Remote', u'cmd': 3, u'id': 55263, u'tristate': u'1FF11F110001', u'time': u'2018-05-08 08:00:26'}
{u'code': u'c0fbeb', u'time': u'2018-05-08 08:00:26', u'learn': 0, u'model': u'Smoke detector GS 558', u'id': 2015, u'unit': 11}
{u'model': u'Akhan 100F14 remote keyless entry', u'data': u'0x8 (Alarm)', u'id': 320238, u'time': u'2018-05-08 08:00:28'}
{u'model': u'Akhan 100F14 remote keyless entry', u'data': u'0x8 (Alarm)', u'id': 320238, u'time': u'2018-05-08 08:00:28'}
{u'model': u'Akhan 100F14 remote keyless entry', u'data': u'0x8 (Alarm)', u'id': 320238, u'time': u'2018-05-08 08:00:29'}
{u'model': u'Akhan 100F14 remote keyless entry', u'data': u'0x8 (Alarm)', u'id': 320238, u'time': u'2018-05-08 08:00:29'}
{u'model': u'Akhan 100F14 remote keyless entry', u'data': u'0x8 (Alarm)', u'id': 320238, u'time': u'2018-05-08 08:00:29'}
{u'model': u'Akhan 100F14 remote keyless entry', u'data': u'0x8 (Alarm)', u'id': 320238, u'time': u'2018-05-08 08:00:29'}
{u'model': u'Akhan 100F14 remote keyless entry', u'data': u'0x8 (Alarm)', u'id': 320238, u'time': u'2018-05-08 08:00:29'}
{u'model': u'Chuango Security Technology', u'cmd': u'Tamper', u'id': 347632, u'cmd_id': 3, u'time': u'2018-05-08 08:00:32'}
{u'model': u'Chuango Security Technology', u'cmd': u'Tamper', u'id': 347632, u'cmd_id': 3, u'time': u'2018-05-08 08:00:32'}
{u'model': u'Chuango Security Technology', u'cmd': u'Tamper', u'id': 347632, u'cmd_id': 3, u'time': u'2018-05-08 08:00:32'}
{u'model': u'Chuango Security Technology', u'cmd': u'Tamper', u'id': 347632, u'cmd_id': 3, u'time': u'2018-05-08 08:00:32'}
{u'model': u'Chuango Security Technology', u'cmd': u'Tamper', u'id': 347632, u'cmd_id': 3, u'time': u'2018-05-08 08:00:32'}
{u'model': u'Chuango Security Technology', u'cmd': u'Tamper', u'id': 347632, u'cmd_id': 3, u'time': u'2018-05-08 08:00:32'}
{u'model': u'Chuango Security Technology', u'cmd': u'Tamper', u'id': 347632, u'cmd_id': 3, u'time': u'2018-05-08 08:00:32'}

**Comment by zuckschwerdt** [comment]
There is no handling for `data, `cmd`, or `tristate` in `publish_sensor_to_mqtt` -- you have to add that as needed.
You seem to be using Python 3, so the `u` indicates the Unicode encoding.
